In [587]:
import pandas as pd
import numpy as np

In [588]:
df = pd.read_excel('data.xlsx')
df

Time - Min  Time - HH:MM:SS  FIC-100 PV  FIC-100 OP  FIC-100 SP  \
0       0.101000  00:00:06.060000  625.009714   49.117879         625   
1       0.206000  00:00:12.360000  625.000575   49.118328         625   
2       0.310500  00:00:18.630000  625.000575   49.118328         625   
3       0.519000  00:00:31.140001  624.996360   49.118000         625   
4       0.623500  00:00:37.410001  625.001699   49.118043         625   
...          ...              ...         ...         ...         ...   
1579  328.383513  05:28:23.010782  625.000119   49.135265         625   
1580  328.489013  05:28:29.340783  625.005298   49.134397         625   
1581  328.800513  05:28:48.030783  624.974535   49.135917         625   
1582  328.904513  05:28:54.270784  625.008296   49.135637         625   
1583  328.904513  05:28:54.270784  625.008296   49.135637         625   

      FIC-101 PV  FIC-101 OP  FIC-101 SP   PIC-100 PV  PIC-100 OP  ...  \
0     367.379063   36.737887  367.378761  2452.998906   63.937867  ...   
1     367.381067   36.738138  367.381572  2453.000860   63.938869  ...   
2     367.381067   36.738138  367.381572  2453.000860   63.938869  ...   
3     367.378381   36.738025  367.384161  2453.002334   63.939632  ...   
4     367.416568   36.742635  367.435024  2453.001245   63.939079  ...   
...          ...         ...         ...          ...         ...  ...   
1579  367.444061   36.744342  367.442863  2452.997660   63.936966  ...   
1580  367.444995   36.744582  367.445475  2452.999275   63.937807  ...   
1581  367.446186   36.744513  367.444595  2452.997872   63.937076  ...   
1582  367.442337   36.744150  367.440784  2452.997344   63.936808  ...   
1583  367.442337   36.744150  367.440784  2452.997344   63.936808  ...   

      Feed Flow  Dist Ethane  Dist Propane  Dist Temp  Dist Pres  Dist Flow  \
0     625.00971      0.95924       0.01878  -10.05458       2010  312.74787   
1     625.00058      0.95924       0.01878  -10.05457       2010  312.74763   
2     625.00058      0.95924       0.01878  -10.05457       2010  312.74763   
3     624.99656      0.95924       0.01878  -10.05458       2010  312.74924   
4     625.00134      0.95924       0.01878  -10.05459       2010  312.75059   
...         ...          ...           ...        ...        ...        ...   
1579  625.01474      0.95924       0.01877  -10.05605       2010  312.68112   
1580  625.00273      0.95924       0.01877  -10.05572       2010  312.67722   
1581  624.99295      0.95924       0.01877  -10.05627       2010  312.67614   
1582  625.00717      0.95924       0.01877  -10.05650       2010  312.67937   
1583  625.00717      0.95924       0.01877  -10.05650       2010  312.67937   

      Bottom Ethane  Bottom Temp  Bottom Pres  Bottom Flow  
0           0.02001     86.34402         1790    312.24911  
1           0.02001     86.34420         1790    312.25297  
2           0.02001     86.34420         1790    312.25297  
3           0.02001     86.34444         1790    312.25081  
4           0.02001     86.34419         1790    312.25185  
...             ...          ...          ...          ...  
1579        0.02000     86.32456         1790    312.32245  
1580        0.02000     86.32442         1790    312.32224  
1581        0.02000     86.32461         1790    312.32139  
1582        0.02000     86.32471         1790    312.32018  
1583        0.02000     86.32471         1790    312.32018  

[1584 rows x 72 columns]

In [589]:
new_df = df[['Time - Min','FIC-100 PV', 'FIC-101 SP']]
# rename the first column to "Time"
new_df.columns = ['Time', 'FIC-100 PV', 'FIC-101 SP']
new_df  


Time  FIC-100 PV  FIC-101 SP
0       0.101000  625.009714  367.378761
1       0.206000  625.000575  367.381572
2       0.310500  625.000575  367.381572
3       0.519000  624.996360  367.384161
4       0.623500  625.001699  367.435024
...          ...         ...         ...
1579  328.383513  625.000119  367.442863
1580  328.489013  625.005298  367.445475
1581  328.800513  624.974535  367.444595
1582  328.904513  625.008296  367.440784
1583  328.904513  625.008296  367.440784

[1584 rows x 3 columns]

In [590]:
def prepare_time_column(df):
    if df['Time'].dtype == np.dtype('O'):
        # # Convert the 'Time' column to a datetime object
        # df['Time'] = pd.to_datetime(df['Time'], errors='coerce')
        def convert_time(value):
            try:
                # Try to convert with microseconds (fractional seconds)
                return pd.to_datetime(value, format='%H:%M:%S.%f')
            except ValueError:
                # Fallback to convert without microseconds
                return pd.to_datetime(value, format='%H:%M:%S')
        
        # Apply conversion and rounding
        df['Time'] = df['Time'].apply(convert_time)
        
        # Round the seconds to two decimal places (100 milliseconds)
        df['Time'] = df['Time'].dt.round('100ms')
        
        # Format the result as 'HH:MM:SS.SS' (up to 2 decimal places for fractional seconds)
        df['Time'] = df['Time'].dt.strftime('%H:%M:%S.%f').str.rstrip('0').str.rstrip('.')
        
        return df
    else:
        return df


In [591]:
test_df = prepare_time_column(new_df)
test_df

Time  FIC-100 PV  FIC-101 SP
0       0.101000  625.009714  367.378761
1       0.206000  625.000575  367.381572
2       0.310500  625.000575  367.381572
3       0.519000  624.996360  367.384161
4       0.623500  625.001699  367.435024
...          ...         ...         ...
1579  328.383513  625.000119  367.442863
1580  328.489013  625.005298  367.445475
1581  328.800513  624.974535  367.444595
1582  328.904513  625.008296  367.440784
1583  328.904513  625.008296  367.440784

[1584 rows x 3 columns]

In [592]:
print(test_df['Time'].dtype)

float64


In [593]:
# use plotly to plot time series data
import plotly.express as px
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(x=test_df['Time'], y=test_df['FIC-100 PV'], mode='lines', name='FIC-100 PV'))
# fig.add_trace(go.Scatter(x=test_df['Time'], y=test_df['FIC-101 SP'], mode='lines', name='FIC-101 SP'))

# Update the layout
if test_df['Time'].dtypes == 'object':
    fig.update_layout(
        xaxis_title='Time',
        yaxis_title='FIC-100 PV',
        xaxis=dict(
            type='date',  # Ensure that the x-axis is treated as a date axis
            tickformat="%H:%M:%S.%f",  # Format the ticks to show time as HH:MM:SS
            # tickmode='auto',
            # nticks=30  # Adjust the number of ticks shown
        )
    )
else:
    fig.update_layout(
        xaxis_title='Time',
        yaxis_title='FIC-100 PV'
    )

fig.show()

In [98]:
df.columns

Index(['Time - Min', 'Time - HH:MM:SS', 'FIC-100 PV', 'FIC-100 OP',
       'FIC-100 SP', 'FIC-101 PV', 'FIC-101 OP', 'FIC-101 SP', 'PIC-100 PV',
       'PIC-100 OP', 'PIC-100 SP', 'LIC-100 PV', 'LIC-100 OP', 'LIC-100 SP',
       'LIC-101 PV', 'LIC-101 OP', 'LIC-101 SP', 'TIC-100 PV', 'TIC-100 OP',
       'TIC-100 SP', 'TIC-101 PV', 'TIC-101 OP', 'TIC-101 SP', 'TIC-102 PV',
       'TIC-102 OP', 'TIC-102 SP', 'XIC-100 PV', 'XIC-100 OP', 'XIC-100 SP',
       'Stage 1', 'Stage 2', 'Stage 3', 'Stage 4', 'Stage 5', 'Stage 6',
       'Stage 7', 'Stage 8', 'Stage 9', 'Stage 10', 'Stage 11', 'Stage 12',
       'Stage 13', 'Stage 14', 'Stage 15', 'Stage 16', 'Stage 17', 'Stage 18',
       'Stage 19', 'Stage 20', 'Stage 21', 'Stage 22', 'Stage 23', 'Stage 24',
       'Stage 25', 'Stage 26', 'Stage 27', 'Stage 28', 'Stage 29', 'Stage 30',
       'Feed Ethane', 'Feed Temp', 'Feed Pres', 'Feed Flow', 'Dist Ethane',
       'Dist Propane', 'Dist Temp', 'Dist Pres', 'Dist Flow', 'Bottom Ethane',
      

In [99]:
new_df = df[['Time - Min','FIC-100 PV', 'FIC-101 SP']]
new_df

Time - Min  FIC-100 PV  FIC-101 SP
0       0.101000  625.009714  367.378761
1       0.206000  625.000575  367.381572
2       0.310500  625.000575  367.381572
3       0.519000  624.996360  367.384161
4       0.623500  625.001699  367.435024
...          ...         ...         ...
1579  328.383513  625.000119  367.442863
1580  328.489013  625.005298  367.445475
1581  328.800513  624.974535  367.444595
1582  328.904513  625.008296  367.440784
1583  328.904513  625.008296  367.440784

[1584 rows x 3 columns]

In [100]:

import pandas as pd

# Convert the 'Time - HH:MM:SS' column to timedelta if not already done
# new_df['Time - HH:MM:SS'] = pd.to_timedelta(new_df['Time - HH:MM:SS'])
new_df['Time - Min'] = pd.to_timedelta(new_df['Time - Min'])

# Calculate the relative time in seconds
new_df['Relative Time (s)'] = (new_df['Time - Min'] - new_df['Time - Min'].iloc[0]).dt.total_seconds()

# Reorder columns to place 'Relative Time (s)' after 'Time - HH:MM:SS'
new_df = new_df[['Time - Min', 'Relative Time (s)', 'FIC-100 PV', 'FIC-101 SP']]

# Display the updated dataframe
new_df




C:\Users\okafo\AppData\Local\Temp\ipykernel_28984\3094121316.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\okafo\AppData\Local\Temp\ipykernel_28984\3094121316.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



Time - Min  Relative Time (s)  FIC-100 PV  FIC-101 SP
0              0 days 00:00:00       0.000000e+00  625.009714  367.378761
1              0 days 00:00:00       0.000000e+00  625.000575  367.381572
2              0 days 00:00:00       0.000000e+00  625.000575  367.381572
3              0 days 00:00:00       0.000000e+00  624.996360  367.384161
4              0 days 00:00:00       0.000000e+00  625.001699  367.435024
...                        ...                ...         ...         ...
1579 0 days 00:00:00.000000328       3.280000e-07  625.000119  367.442863
1580 0 days 00:00:00.000000328       3.280000e-07  625.005298  367.445475
1581 0 days 00:00:00.000000328       3.280000e-07  624.974535  367.444595
1582 0 days 00:00:00.000000328       3.280000e-07  625.008296  367.440784
1583 0 days 00:00:00.000000328       3.280000e-07  625.008296  367.440784

[1584 rows x 4 columns]

In [1]:
import numpy as np

# Original array
values = np.arange(20, 65, 5)

# Old and new min/max values
old_min, old_max = 20, 60
new_min, new_max = 5, 100

# Scaling formula
scaled_values = ((values - old_min) * (new_max - new_min) / (old_max - old_min)) + new_min

scaled_values


array([  5.   ,  16.875,  28.75 ,  40.625,  52.5  ,  64.375,  76.25 ,
        88.125, 100.   ])

In [2]:
values

array([20, 25, 30, 35, 40, 45, 50, 55, 60])

In [3]:
scaled_values

array([  5.   ,  16.875,  28.75 ,  40.625,  52.5  ,  64.375,  76.25 ,
        88.125, 100.   ])